spring.application.name=incidencias
# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/incidencias_db
spring.datasource.username=admin
spring.datasource.password=adminpassword

# Configuración de Hibernate (El ORM)
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true